### ISSUE TITLE
Feature Request Split Most Recent Year

### ISSUE THREAD

**Issue by xmoforf** [lewler/bulldozer#20]
I was thinking a nice feature would be to split off the most recent year of **incomplete** shows to a separate bundle. So if a show has been running since 2011, 2011-2023 would go into a bundle then 2024-present in the other.

**Comment by lewler** [comment]
Interesting concept. I will think about it, and how it might be implemented.

**Comment by lewler** [comment]
This has been implemented in v0.6.0
